"""Template renderers for first-run setup output files."""

from .models import SetupAnswers


def _toml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_bool(value: bool) -> str:
    return "true" if value else "false"


def render_config_template(answers: SetupAnswers) -> str:
    """Render a fully-commented configuration template."""
    refresh_on_startup = answers.cookie_source == "browser"

    return f"""# ytdl-archiver configuration
# Generated by: ytdl-archiver init
#
# Edit this file to tune global defaults for all playlists.
# Playlist-specific overrides belong in playlists.toml.

[archive]
# Base output directory for all playlist folders.
base_directory = {_toml_str(answers.archive_directory)}
# Delay between individual video downloads (seconds).
delay_between_videos = 10
# Delay between processing each playlist (seconds).
delay_between_playlists = 30
# Retry count for transient download failures.
max_retries = 3
# Exponential retry multiplier.
retry_backoff_factor = 2.0

[download]
# yt-dlp format selector.
format = "bestvideo+bestaudio/best"
# Final container when merging.
merge_output_format = "mp4"
# Download subtitles when available.
write_subtitles = {_toml_bool(answers.write_subtitles)}
# Subtitle format to request from yt-dlp.
subtitle_format = "vtt"
# Convert subtitles to this format after download.
convert_subtitles = "srt"
# Preferred subtitle language list.
subtitle_languages = ["en"]
# Download video thumbnails.
write_thumbnail = {_toml_bool(answers.write_thumbnail)}
# Thumbnail image format.
thumbnail_format = "jpg"
# Number of concurrent downloads (keep 1 unless you know you need more).
max_concurrent_downloads = 1

[filename]
# Ordered filename tokens. Supported: title, channel, upload_date, video_id
tokens = ["title", "channel"]
# Joiner between top-level tokens.
token_joiner = "_"
# Date rendering format for upload_date token.
# Supported: yyyy-mm-dd, yyyymmdd, yyyy_mm_dd, yyyy.mm.dd
date_format = "yyyy-mm-dd"
# Missing token handling (v1 supports only "omit").
missing_token_behavior = "omit"

[filename.case]
# Case mode per token: preserve, lower, upper, title
title = "lower"
channel = "lower"
upload_date = "preserve"
video_id = "lower"

[shorts]
# Detect portrait videos as Shorts and place into a subdirectory.
detect_shorts = true
# Relative subdirectory name for Shorts.
shorts_subdirectory = "YouTube Shorts"
# Width/height ratio threshold for Shorts detection.
aspect_ratio_threshold = 0.7

[logging]
# One of: DEBUG, INFO, WARNING, ERROR, CRITICAL
level = "INFO"
# Structured logger format.
format = "json"
# Application log file.
file_path = "~/.local/share/ytdl-archiver/logs/app.log"
# Log rotation size.
max_file_size = "10MB"
# Number of rotated files to keep.
backup_count = 5

[http]
# User agent used by yt-dlp HTTP requests.
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
request_timeout = 30
connect_timeout = 10
# Path to cookies file consumed by yt-dlp.
cookie_file = "~/cookies.txt"

[cookies]
# Cookie source:
# - "manual_file": maintain ~/cookies.txt yourself
# - "browser": refresh cookies from a browser before archive runs
source = {_toml_str(answers.cookie_source)}
# Browser for refresh mode. Supported values:
# firefox, chrome, chromium, brave, edge, opera, vivaldi, whale, safari
browser = {_toml_str(answers.cookie_browser)}
# Optional profile name or absolute profile path.
profile = {_toml_str(answers.cookie_profile)}
# If true and source="browser", refresh cookies before archive runs.
refresh_on_startup = {_toml_bool(refresh_on_startup)}

[media_server]
# Create .nfo sidecars for media server metadata.
generate_nfo = {_toml_bool(answers.generate_nfo)}
# NFO output style.
nfo_format = "kodi"
"""


def render_playlists_template() -> str:
    """Render playlists template with one ready-to-edit example."""
    return """# playlists.toml
# Add one [[playlists]] entry per channel/playlist to archive.
#
# How to get the id:
# - Channel uploads playlist IDs usually start with "UU..."
#   - You can get them by copying the channel ID from the Share options
#     at the bottom of the channel description pop-up (on youtube dot
#     com) and replaced the second letter with another U.
# - Playlist URLs look like:
#   https://www.youtube.com/playlist?list=PLAYLIST_ID
#
# path is relative to archive.base_directory from config.toml.

[[playlists]]
id = "UUxxxxxxxxxxxxxxxxxxxxxx"
path = "Example Channel"
name = "Example Channel Uploads"

[playlists.download]
# Optional per-playlist overrides:
# format = "bestvideo[height<=1080]+bestaudio/best[height<=1080]"
# write_subtitles = true
# subtitle_languages = ["en"]
# write_thumbnail = true
"""
